### PR TITLE
Readibility Patch

### LINKED ISSUE #2: Typos in README
Find and fix as many typographical and grammatical errors as you can.

### PR DESCRIPTION
**Pull request by JScrips**
Updated Readability of README
fixes #2

### CODE REVIEW

**Comment by balotofi** [comment]
There's still a typo in the example format but I'll merge this first

**Comment by JScrips** [comment]
You are corerct, I could edit that quickly if you'd like

**Comment by JScrips** [comment]
I also believe it's possible for you to make edits to my submission

**Comment by balotofi** [comment]
Yes I can actually but I've already merged. I'll do that edit later

**Pull request merged**
